import Navbar from "./Components/navbar/Navbar"

const App = () => {
  return (
    <div className="b">
      <Navbar />
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, cumque magnam, debitis reiciendis illo quis, asperiores quia excepturi atque aperiam voluptatem. Doloribus commodi quam accusantium omnis tempore consequatur perspiciatis sint? Neque a itaque ab assumenda aperiam dignissimos, eius, quas iste corrupti velit, rerum quod obcaecati? Rerum sapiente itaque esse odio, reprehenderit officia. Minima, molestias. Recusandae assumenda veritatis ut, sunt esse, fuga eius iste necessitatibus, eligendi delectus magnam molestiae fugit tempora? Maxime, iure eligendi cupiditate rerum, consequatur quae illum repudiandae nostrum corrupti quaerat nesciunt doloribus possimus recusandae? Qui ipsum perferendis exercitationem, officiis iste ipsam aspernatur modi? Itaque dolorem et soluta molestias maiores accusamus, adipisci vel fugiat voluptate qui quibusdam in nihil eius asperiores, quos quidem odit deleniti blanditiis. Delectus molestiae omnis sit, veritatis mollitia asperiores alias. Dolorem commodi tenetur iure officia facere saepe, dolore mollitia accusantium repellat tempora, quasi quas rem modi qui? Aliquam delectus culpa, aspernatur nesciunt nulla rem corrupti dignissimos dolore beatae dolorem. Expedita distinctio explicabo accusantium accusamus eos vel ipsam maiores, doloremque autem corporis, doloribus eum aspernatur! Quam dolorem expedita minus iusto beatae alias facilis hic? Laudantium quod velit similique qui rem aliquam perferendis adipisci, ab eveniet. Libero, ipsam nihil, eaque aliquam fugit ex quod accusamus voluptas doloribus mollitia eos, delectus quibusdam ducimus inventore. Ab ex nobis necessitatibus est voluptas eveniet doloribus voluptate. Ipsa inventore, aliquid hic porro possimus saepe ea in suscipit, explicabo eaque rerum quas doloribus labore debitis quae doloremque sapiente? Debitis quia repudiandae nemo numquam quaerat nostrum eum at nisi expedita officiis quibusdam voluptas ipsa quas id, voluptate velit. Delectus harum in iste officia aperiam, sunt cupiditate? Eum, iste ipsam odio, amet atque voluptatum explicabo, quidem ipsa neque ipsum repellendus totam! Consequatur ad corporis natus quidem. Hic pariatur ut quas? Sint delectus dolores in deleniti, molestiae, iusto eligendi amet consequuntur ab quidem aperiam quasi iure, hic corrupti! Nobis tempora itaque quae, libero, atque laudantium voluptas voluptatem dicta officia voluptatibus enim assumenda blanditiis repellendus obcaecati similique praesentium repudiandae! Excepturi velit repudiandae quod, architecto molestiae cumque consequuntur rem atque laudantium explicabo incidunt eveniet beatae odio possimus ea, ipsum obcaecati adipisci nulla.
    </div>
  )
}

export default App
